import manifest from "./achievements-media.json";
import { portfolio, type Achievement } from "./portfolio";

// Generated by scripts/build-achievements.mjs — don't edit the JSON by hand.

export interface MediaItem {
  type: "image" | "video" | "pdf";
  name: string;
  src: string;
  thumb?: string;
  poster?: string;
  width?: number;
  height?: number;
  duration?: number;
  color?: string;
  /** Tiny blurred data-URL preview for blur-up loading. */
  blur?: string;
}

interface Manifest {
  folders: Record<string, { slug: string; items: MediaItem[] }>;
}

const folders = (manifest as Manifest).folders ?? {};

export const mediaFor = (a: Pick<Achievement, "mediaFolder">): MediaItem[] =>
  (a.mediaFolder && folders[a.mediaFolder]?.items) || [];

/** Media folders not linked to any achievement, shown under "Other highlights". */
export const otherHighlights = (): { id: string; name: string; items: MediaItem[] }[] => {
  const used = new Set(portfolio.achievements.map((a) => a.mediaFolder).filter(Boolean));
  return Object.entries(folders)
    .filter(([name, f]) => !used.has(name) && f.items.length > 0)
    .map(([name, f]) => ({ id: `other-${f.slug}`, name, items: f.items }));
};

export const coverFor = (items: MediaItem[]): MediaItem | undefined =>
  items.find((i) => i.type === "image") ?? items.find((i) => i.type === "video");

export const mediaSummary = (items: MediaItem[]): string => {
  const count = (t: MediaItem["type"]) => items.filter((i) => i.type === t).length;
  const parts: string[] = [];
  const photos = count("image");
  const videos = count("video");
  const docs = count("pdf");
  if (photos) parts.push(`${photos} photo${photos > 1 ? "s" : ""}`);
  if (videos) parts.push(`${videos} video${videos > 1 ? "s" : ""}`);
  if (docs) parts.push(`${docs} document${docs > 1 ? "s" : ""}`);
  return parts.join(" · ");
};
