import manifest from "./previews.json";

// Generated by scripts/capture-previews.mjs — screenshots of each live project site.
export interface Preview {
  src: string;
  srcSm: string;
  width: number;
  height: number;
  color: string;
  url: string;
}

const previews = manifest as Record<string, Preview>;

export const previewFor = (projectId: string): Preview | undefined => previews[projectId];
export const previewForUrl = (url: string): Preview | undefined =>
  Object.values(previews).find((p) => p.url === url);
