import manifest from "./previews.json";
import { portfolio } from "./portfolio";

// Generated by scripts/capture-previews.mjs — screenshots of each live project site.
export interface Preview {
  src: string;
  srcSm: string;
  width: number;
  height: number;
  color: string;
  url: string;
}

const previews = manifest as Record<string, Preview>;

const sameSite = (a: string, b: string): boolean => {
  try {
    const ua = new URL(a);
    const ub = new URL(b);
    return ua.hostname.replace(/^www\./, "") === ub.hostname.replace(/^www\./, "") && ua.pathname === ub.pathname;
  } catch {
    return false;
  }
};

/** Screenshot for a project (undefined when none has been captured yet). */
export const previewFor = (projectId: string): Preview | undefined => previews[projectId];

/**
 * Screenshot for a URL: an exact capture of that page, or else the capture of the
 * project that owns the URL (so a project's new address still finds its screenshot).
 */
export const previewForUrl = (url: string): Preview | undefined => {
  const direct = Object.values(previews).find((p) => sameSite(p.url, url));
  if (direct) return direct;
  const owner = portfolio.projects.find((p) => p.url && sameSite(p.url, url));
  return owner ? previews[owner.id] : undefined;
};
